### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by syreal17** [irontoby/shuttleit#1]
This worked perfectly for me on my new Ubuntu 20.04 laptop. Your documentation is really good, thank you so much!

Honestly, I think this experience has been a lot better than the official software from the maker of ShuttleXpress. Getting the device to work on Windows (on my last computer) was marginally faster than your repo on my new computer, but configuring the device on Windows is a complete bitch and designed for nothing more sophisticated than brute-force pointing and clicking... I suppose I'm grateful for knowing all of the different events that the ShuttleXpress detects that was pretty obvious in the Windows GUI configuration tool and there were many more than I would've expected, but nonetheless predicting what they actually meant was non-trivial. I haven't re-jiggered anything from your original `shuttleit.pl`, but upon a brief inspection, I've very glad to have some programmtic control over this "special" device that is pretty darn useful.

I definitely support Perl over Go, btw, fwiw, haha

**Comment by irontoby** [comment]
@syreal17 glad it worked out well for you!

I was also glad I bothered to write up docs when I installed 20.04 from scratch and had pretty much forgotten all the tinkering I'd done 5 years prior. Here's hoping it still works in 2022, haha...

**Comment by syreal17** [comment]
@irontoby One of my biggest uses for the ShuttleXpress is the "ring" as a mouse scroll wheel, however, I don't find anything in `shuttleit.pl` that processes the state of the "ring" input. Is acting as a mouse wheel somehow default behavior for that input?

**Comment by syreal17** [comment]
Oh interesting, I just killed the script and nothing besides scroll works now...

**Comment by irontoby** [comment]
Sorry I just saw this question, I'm not aware of anything different about the ring wheel. I don't really remember why I decided to not keep the state of the ring wheel but it looks like [this fork](https://github.com/sivaprakasaman/shuttleit) has added some code to do that so you may want to try that.

I'll close this issue since GitHub now has [Discussions](https://github.com/irontoby/shuttleit/discussions), that's probably a better place to ask questions if needed, but I'm not sure how much help I'll be!
